---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluevelvet
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # 字体
  - type: fonts
    fonts:
      url-fonts:
        - name: 更纱黑体
          url: https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.36/Sarasa-SuperTTC-1.0.36.7z

  # RPM 包
  - type: dnf
    install:
      packages:
        - uxplay

  # 默认 Flatpak
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - page.tesk.Refine
          - app.fotema.Fotema
          - com.gopeed.Gopeed
          - info.febvre.Komikku
          - it.mijorus.gearlever
          - org.gnome.Fractal
          - org.gnome.World.PikaBackup
          - org.localsend.localsend_app
          - io.github.flattool.Ignition
          - io.github.Foldex.AdwSteamGtk
          - io.github.IshuSinghSE.aurynk
          - io.github.ilya_zlobintsev.LACT
          - io.github.celluloid_player.Celluloid
          - com.qq.QQ
          - com.tencent.WeChat
          - com.vivaldi.Vivaldi
          - com.bitwarden.desktop
          - com.heroicgameslauncher.hgl
          - org.equicord.equibop
          - io.podman_desktop.PodmanDesktop
        remove:
          - org.mozilla.firefox
          - org.altlinux.Tuner
      - notify: true
        scope: system
        repo:
          name: geforcenow
          url: https://international.download.nvidia.com/GFNLinux/flatpak/geforcenow.flatpakrepo
          title: "GeForce NOW Official"
        install:
          - com.nvidia.geforcenow

  # Gnome 扩展
  - type: gnome-extensions
    install:
      - UXPlay Control

  # 修复键盘F键
  - type: kargs
    kargs:
      - hid_apple.fnmode=2

  # 系统配置
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # just 脚本
  - type: justfiles
    validate: true
    install: true
    include:
      - custom.just

  # 签名 OCI 镜像
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
