---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# 映像将发布到 ghcr.io/<user>/<name>
name: bluevelvet
# 描述信息将包含在映像的元数据中
description: 这是我的个人系统映像

# 要构建的基础映像和要使用的版本标签
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia-gnome
image-version: latest

# 模块配置，按顺序执行
# 您可以包含同一模块的多个实例
modules:
  # 通过 DNF 安装
  - type: dnf
    install:
      packages:
        - uxplay
        - ibus-rime
        - https://github.com/xishang0128/sparkle/releases/download/1.26.3/sparkle-linux-1.26.3-x86_64.rpm
    remove:
      packages:
        - lutris.x86_64 

  # 添加 GNOME 扩展
  - type: gnome-extensions
    install:
      - UXPlay Control

  # 通过 Flatpak 安装
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - page.tesk.Refine
          - app.drey.Dialect
          - app.fotema.Fotema
          - info.febvre.Komikku
          - it.mijorus.gearlever
          - org.zotero.Zotero
          - org.gnome.Maps
          - org.gnome.Fractal
          - org.gnome.World.PikaBackup
          - org.localsend.localsend_app
          - io.github.flattool.Ignition
          - io.github.Foldex.AdwSteamGtk
          - io.github.IshuSinghSE.aurynk
          - io.github.ilya_zlobintsev.LACT
          - io.github.Faugus.faugus-launcher
          - io.mpv.Mpv
          - com.gopeed.Gopeed
          - com.sidevesh.Luminance
          - net.trowell.typesetter
          - io.github.totoshko88.RustConn
          - re.sonny.Tangram
          - com.github.johnfactotum.Foliate
          - io.github.vikdevelop.SaveDesktop
          - com.github.marhkb.Pods

  # 添加系统文件
  - type: files
    files:
      - source: system
        destination: /

  # 添加 just 脚本
  - type: justfiles
    validate: true
    include:
      - bluevelvet.just

  # 启用 systemd 服务
  - type: systemd
    user:
      enabled:
        - rime-ice.service

  # 初始化initramfs
  - type: initramfs

  # 签名 OCI 镜像
  - type: signing