---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluevelvet
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      files:
        - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
      copr:
        - ronnypfannschmidt/howdy-beta
    install:
      packages:
        - uxplay
        - howdy
        - howdy-gtk
        - vivaldi-stable
        - https://github.com/xishang0128/sparkle/releases/download/1.6.16/sparkle-linux-1.6.16-x86_64.rpm
  # remove:
  #   packages:
  #     -

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - page.tesk.Refine
          - app.fotema.Fotema
          - com.gopeed.Gopeed
          - info.febvre.Komikku
          - it.mijorus.gearlever
          - org.gnome.Fractal
          - org.gnome.World.PikaBackup
          - org.localsend.localsend_app
          - io.github.flattool.Ignition
          - io.github.Foldex.AdwSteamGtk
          - io.github.IshuSinghSE.aurynk
          - io.github.ilya_zlobintsev.LACT
          - io.github.celluloid_player.Celluloid
        remove:
          - org.mozilla.firefox
          - org.altlinux.Tuner
  #    - scope: user # Also add Flathub user repo, but no user packages

  - type: gnome-extensions
    install:
      - UXPlay Control

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      - source: justfile
        destination: /usr/share/ublue-os/just/60-custom.just

  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
