---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluevelvet
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia-open
image-version: testing # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
      copr:
        - ronnypfannschmidt/howdy-beta
    install:
      packages:
        - howdy
        - howdy-gtk
        - vivaldi-stable
  #   remove:
  #     packages:
  #       -

  - type: script
    scripts:
      - clash-party.sh

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - page.tesk.Refine
          - app.fotema.Fotema
          - com.gopeed.Gopeed
          - it.mijorus.gearlever
          - org.gnome.World.PikaBackup
          - org.localsend.localsend_app
          - io.github.flattool.Ignition
          - io.github.ilya_zlobintsev.LACT
          - io.github.celluloid_player.Celluloid
          - com.qq.QQ
          - com.tencent.WeChat
          - com.bitwarden.desktop
          - com.discordapp.Discord
          - io.github.pol_rivero.github-desktop-plus
        remove:
          - org.mozilla.firefox
          - org.gnome.Showtime
          - org.gnome.TextEditor
          - org.gnome.Loupe
          - org.altlinux.Tuner
          - io.github.flattool.Warehouse
  #    - scope: user # Also add Flathub user repo, but no user packages

  - type: systemd
    user:
      enabled:
        - first-login-setup.service

  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
