---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# 映像将发布到 ghcr.io/<user>/<name>
name: bluevelvet
# 描述信息将包含在映像的元数据中
description: 这是我的个人系统映像

# 要构建的基础映像和要使用的版本标签
base-image: ghcr.io/ublue-os/bazzite-deck-nvidia-gnome
image-version: latest

# 模块配置，按顺序执行
# 您可以包含同一模块的多个实例
modules:
  # 添加系统配置
  - type: files
    files:
      - source: system
        destination: /

  # 注入内核参数
  - type: kargs
    kargs:
      - hid_apple.fnmode=2
      - systemd.zram=0
      - zswap.enabled=1
      - zswap.shrinker_enabled=1

  # 添加字体
  - type: fonts
    fonts:
      url-fonts:
        - name: 更纱黑体 UI SC
          url: https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.37/SarasaUiSC-TTF-1.0.37.7z

  # 通过 DNF 安装
  - type: dnf
    install:
      packages:
        - uxplay
        - ibus-rime
        - https://github.com/xishang0128/sparkle/releases/download/1.26.3/sparkle-linux-1.26.3-x86_64.rpm

  # 通过 Flatpak 安装
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        repo:
          name: flathub
          url: https://mirrors.ustc.edu.cn/flathub
        install: # system flatpaks we want all users to have and not remove
          - app.drey.Dialect
          - app.fotema.Fotema
          - info.febvre.Komikku
          - it.mijorus.gearlever
          - org.zotero.Zotero
          - org.gnome.Maps
          - org.gnome.Fractal
          - org.gnome.World.PikaBackup
          - org.localsend.localsend_app
          - io.github.flattool.Ignition
          - io.github.Foldex.AdwSteamGtk
          - io.github.IshuSinghSE.aurynk
          - io.github.ilya_zlobintsev.LACT
          - io.github.Faugus.faugus-launcher
          - io.mpv.Mpv
          - com.gopeed.Gopeed
          - com.bitwarden.desktop
          - com.sidevesh.Luminance
          - net.trowell.typesetter
          - org.qbittorrent.qBittorrent
          - com.github.wwmm.easyeffects
          - io.github.totoshko88.RustConn
          - re.sonny.Tangram
          - com.github.johnfactotum.Foliate
          - net.shadps4.shadPS4

  # 添加 GNOME 扩展
  - type: gnome-extensions
    install:
      - UXPlay Control

  # 签名 OCI 镜像
  - type: signing
