---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluevelvet
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia-gnome
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # 添加字体
  - type: fonts
    fonts:
      google-fonts:
        - Inter Tight
      url-fonts:
        - name: 更纱黑体 UI SC
          url: https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.36/SarasaUiSC-TTF-1.0.36.7z

  # 通过 DNF 安装
  - type: dnf
    install:
      packages:
        - uxplay
        - ibus-rime
        - https://github.com/xishang0128/sparkle/releases/download/1.26.1/sparkle-linux-1.26.1-x86_64.rpm

  # 通过 Flatpak 安装
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - page.tesk.Refine
          - app.drey.Dialect
          - app.fotema.Fotema
          - com.gopeed.Gopeed
          - com.github.marhkb.Pods
          - info.febvre.Komikku
          - it.mijorus.gearlever
          - org.gnome.Fractal
          - org.gnome.World.PikaBackup
          - org.localsend.localsend_app
          - io.github.flattool.Ignition
          - io.github.Foldex.AdwSteamGtk
          - io.github.IshuSinghSE.aurynk
          - io.github.ilya_zlobintsev.LACT
          - io.github.Faugus.faugus-launcher
          - io.github.celluloid_player.Celluloid
          - com.qq.QQ
          - com.tencent.WeChat
          - com.vivaldi.Vivaldi
          - com.bitwarden.desktop
          - org.equicord.equibop
        remove:
          - org.mozilla.firefox
          - org.altlinux.Tuner
      - notify: true
        scope: system
        repo:
          name: GeForceNOW
          title: "GeForce NOW 官方"
          url: https://international.download.nvidia.com/GFNLinux/flatpak/geforcenow_repo
        install:
          - com.nvidia.geforcenow

  # 添加 GNOME 扩展
  - type: gnome-extensions
    install:
      - UXPlay Control

  # 安装 GNOME 主题
  - type: script
    scripts:
      - theme.sh

  # 注入内核参数
  - type: kargs
    kargs:
      - hid_apple.fnmode=2

  # 添加系统配置
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # 通过 Homebrew 安装
  - type: systemd
    user:
      enabled:
        - setup-brew.service

  # 添加 just 脚本
  - type: justfiles
    validate: true
    install: true
    include:
      - bluevelvet.just

  # 签名 OCI 镜像
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
